export const editorOptions = {
  readOnly: false,
  // bounds: '.' + gridBem.block(),
  theme: 'snow',
  modules: {
    toolbar: [
      [
        { header: '1' },
        { header: '2' },
        { font: ['', 'open-sans', 'roboto', 'proza-libre'] },
        { size: ['1em', '1.25em', '1.5em', '2em', '3em', '4em'] },
      ],
      ['bold', 'italic', 'underline'],
      [{ color: [] }, { background: [] }],
      [{ align: ['', 'center', 'right'] }],
      [{ list: 'ordered' }, { list: 'bullet' }],
    ],
  },
  formats: [
    'align',
    'background',
    'header',
    'font',
    'size',
    'align',
    'bold',
    'italic',
    'underline',
    'strike',
    'script',
    'list',
    'bullet',
    'indent',
    'link',
    'color',
    'clean',
  ],
};
